server:
  port: 9999
  servlet:
    context-path: "/api/v1"
---
spring:
  config:
    activate:
      on-profile: "sql"
  flyway:
    user: "databaseUser"
    password: "databasePassword"
    schemas: "app-db"
    url: "jdbc:h2:mem:DATABASE"
    locations: "filesystem:db/migration"
server:
  port: 9998
