server:
  port: 9999
  servlet:
    context-path: "/api/v1"
---
spring:
  config:
    activate:
      on-profile: "sql"
  flyway:
    user: "sa"
    password: ""
    schemas: "app-db"
    url: "jdbc:h2:mem:test"
    locations: "filesystem:db/migration"
  datasource:
    url: "jdbc:h2:mem:test"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""
  h2:
    console:
      enabled: true
      path: "/h2"
